[package]
name = "foodhut_backend_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
apalis = { version = "0.5.3", features = ["redis", "cron", "retry"] }
async-convert = "1.0.0"
async-trait = "0.1.81"
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
axum_typed_multipart = "0.11.1"
base16ct = { version = "0.2.0", features = ["alloc"] }
base64 = "0.22.1"
bigdecimal = { version = "0.3.0", features = ["serde"] }
bytes = "1.6.0"
chrono = { version = "0.4.38", features = ["serde"] }
cloudinary = "0.4.0"
crypto-common = "0.1.6"
env_logger = "0.11.3"
futures = "0.3.30"
google-fcm1 = "6.0.0"
headers = "0.4.0"
hex = "0.4.3"
hmac = "0.12.1"
hyper = "1.4.1"
itertools = "0.13.0"
lettre = { version = "0.11.7", features = [
    "tokio1",
    "builder",
    "tokio1-native-tls",
] }
log = "0.4.22"
num-bigint = "0.4.6"
oauth_fcm = "0.3.0"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["json", "multipart"] }
serde = { version = "1.0.203", features = ["derive"] }
serde-aux = "4.5.0"
serde_json = "1.0.120"
sha1 = "0.10.6"
sha2 = "0.10.8"
sqlx = { version = "0.7.4", features = [
    "postgres",
    "runtime-tokio",
    "chrono",
    "macros",
    "bigdecimal",
] }
tempfile = "3.10.1"
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = "0.7.11"
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["cors", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["std", "env-filter"] }
ulid = "1.1.2"
uri_parser = "0.2.0"
urlencoding = "2.1.3"
validator = { version = "0.18.1", features = ["derive"] }

# [[test]]
# name = "integration"
# path = "tests/integration/mod.rs"
