# fly.toml app configuration file generated for foodhut-backend-rs on 2024-07-05T22:43:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'foodhut-backend-rs'
primary_region = 'ams'

[build]

[env]
  PORT = 8080

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  processes = ['app']

[checks]
  [checks.api]
    port = 8080
    type = 'http'
    interval = '120s'
    timeout = '30s'
    grace_period = '60s'
    method = 'get'
    path = '/api'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
