# fly.toml app configuration file generated for foodhut on 2024-07-05T22:49:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'foodhut'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'
  DATABASE_URL = 'postgres://foodhut:RAf1vmHQILdKMcj@foodhut-db.flycast:5432/foodhut?sslmode=disable'
  SQLX_OFFLINE = true

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  processes = ['app']

[checks]
  [checks.api]
    port = 8080
    type = 'http'
    interval = '2m0s'
    timeout = '30s'
    grace_period = '1m0s'
    method = 'get'
    path = '/api'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
